language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - phpenv rehash
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - mysql -e 'create database IF NOT EXISTS pyrocms;'
  - export PYRO_DB_HOST=127.0.0.1
  - export PYRO_DB_USER=travis
  - export PYRO_DB_PASS=
  - export PYRO_WEB_HOST=127.0.0.1

  - chmod -R 777 system/cms/cache
  - chmod -R 777 system/cms/config
  - chmod -R 777 addons
  - chmod -R 777 assets/cache
  - chmod -R 777 uploads

script: phpunit -c tests/integration

branches:
  exclude:
    - 2.1/develop
    - 2.1/master
    - 2.0/develop
    - 2.0/master