language: php
php:
  - "5.3.3"
  - "5.4"
before_script:
  - "sudo chmod -R 777  ."
  - "sudo apt-get install apache2"
  - "sudo a2enmod actions"
  - "sudo a2enmod rewrite"
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://raw.github.com/gist/16d751c979fdeb5a14e3/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://raw.github.com/gist/2eb301570ed4a1f4c33d/gistfile1.txt)" | sed -e "s,PATH,`pwd`,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - "sudo service apache2 restart"
  - mysql -u root -e "CREATE USER 'pyrocms'@'127.0.0.1' IDENTIFIED BY 'password'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* to 'pyrocms'@'127.0.0.1' IDENTIFIED BY 'password'"
script: phpunit -c tests/integration

branches:
  exclude:
    - 2.1/develop
    - 2.1/master
    - 2.0/develop
    - 2.0/master
